homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam
  # Customization file
  customize: !include customize.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Show the introduction message on startup.
introduction:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google

### COMPONENTS ########################
device_tracker:
  - platform: fritz

discovery:

ios:

logger:
  default: info
  logs:
    homeassistant.components.mysensors: debug
    mysensors: debug

mysensors:
  gateways:
    - device: '0.0.0.0'
      tcp_port: 5003
  version: '2.3.1'

rflink:
  port: /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0

sun:
  
system_health:

weather:
- platform: darksky
  api_key: !secret darksky_api_key
  name: Weer
  mode: daily

### DEVICES ###########################
light: !include config/light.yaml

sensor: !include config/sensor.yaml

#######################################
group: !include groups.yaml
automation: !include automations.yaml
automation old: !include_dir_merge_list config/automations
script: !include scripts.yaml
